In [1]:
import numpy as np

In [2]:
arr1 = [2, 3, 4]
print(type(arr1))
arr1 = np.array(arr1)
print(type(arr1))
arr1

<class 'list'>
<class 'numpy.ndarray'>


array([2, 3, 4])

In [4]:
np.ndim(arr1)

1

In [6]:
arr1.dtype

dtype('int32')

In [10]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [13]:
b = np.arange(10)
b **= 3
b

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [16]:
c = np.linspace(0, 24, 6)
c

array([ 0. ,  4.8,  9.6, 14.4, 19.2, 24. ])

In [18]:
d = np.linspace(0, 45, 8, endpoint=False)
d

array([ 0.   ,  5.625, 11.25 , 16.875, 22.5  , 28.125, 33.75 , 39.375])